- name: My first play
  hosts: myhosts
  tasks:
   - name: Install apache httpd (state=present is optional)
     ansible.builtin.apt:
       name: apache2
       state: present

   - name: Print message
     ansible.builtin.debug:
       msg: Hello world
