- name: My apt
  hosts: myhosts
  tasks:
   - name: App things
     ansible.builtin.apt:
       update_cache: yes
       upgrade: yes
       autoremove: yes
       

   - name: Print message
     ansible.builtin.debug:
       msg: Hello world
